"""AxiomBraid 2.0.0 final-release hardening tests."""

from __future__ import annotations
import json
import os
from pathlib import Path
import subprocess
import sys
import pandas as pd
import axiombraid as AB

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

ROOT = Path(__file__).resolve().parents[1]


def _frame() -> pd.DataFrame:
    return pd.DataFrame({
        "Employee_ID": [1, 2, 3, 4, 5],
        "Age": [25, 26, 27, 28, 29],
        "Department": ["HR", "HR", "IT", "IT", "Sales"],
        "Salary": [50000, 52000, 54000, 56000, 58000],
        "JoinDate": ["2024-01-01", "2024-02-01", "2024-03-01", "2024-04-01", "2024-05-01"],
    })


def test_final_release_metadata_is_stable():
    assert AB.__version__ == "2.0.0"
    assert AB.VERSION_INFO == (2, 0, 0)
    assert AB.API_STATUS == "stable"
    assert AB.PUBLIC_API_VERSION == "2"
    assert AB.RELEASE_STAGE == "stable"


def test_pyproject_version_and_classifier_match_runtime():
    metadata = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    assert metadata["project"]["version"] == AB.__version__
    assert "Development Status :: 5 - Production/Stable" in metadata["project"]["classifiers"]
    assert metadata["project"]["urls"]["Repository"].endswith("Adil307/AxiomBraid")


def test_cli_reports_final_version():
    environment = os.environ.copy()
    environment["PYTHONPATH"] = str(Path(AB.__file__).parents[1])
    completed = subprocess.run([sys.executable, "-m", "axiombraid", "--version"], capture_output=True, text=True, check=False, env=environment)
    assert completed.returncode == 0
    assert completed.stdout.strip() == "AxiomBraid 2.0.0"


def test_about_and_self_check_report_stable_release():
    about = AB.about()
    assert about["version"] == "2.0.0"
    assert about["api_status"] == "stable"
    assert about["release_stage"] == "stable"
    check = AB.self_check()
    assert check["ok"] is True
    names = {item["name"] for item in check["checks"]}
    expected = {"core_inspection", "confidence_reporting", "quality_profile", "non_destructive_corruption", "public_api_compatibility", "python_supported"}
    assert expected <= names


def test_version1_compatible_workflow_remains_functional(tmp_path):
    frame = _frame()
    inspection = AB.inspect(frame)
    assert inspection["shape"] == {"rows": 5, "columns": 5}
    cleaned = AB.clean(frame, risk="low")
    assert isinstance(cleaned, pd.DataFrame)
    validation = AB.validate(frame, {"Age": {"minimum": 0, "maximum": 120}})
    assert validation["valid"] is True
    comparison = AB.compare(frame, cleaned)
    assert isinstance(comparison, dict)
    html = AB.export_html(frame, tmp_path / "report.html")
    assert "Generated by AxiomBraid 2.0.0" in html.read_text(encoding="utf-8")


def test_version2_complete_workflow_is_json_serializable():
    frame = _frame()
    inspection = AB.inspect(frame, include_confidence=True, include_quality_profile=True)
    json.dumps(inspection, default=str)
    corrupted, truth = AB.inject_issues(frame, missing_rate=0.1, duplicate_rate=0.2, invalid_range_rate=0.1, random_state=42)
    assert not corrupted.equals(frame)
    evaluation = AB.run_evaluation(frame, corruption_config={"missing_rate": 0.1, "duplicate_rate": 0.2, "invalid_range_rate": 0.1, "random_state": 42})
    json.dumps(evaluation["detection_evaluation"])
    assert truth["events"]


def test_corruption_is_reproducible_and_non_destructive():
    frame = _frame()
    original = frame.copy(deep=True)
    first, first_truth = AB.inject_issues(frame, missing_rate=0.2, duplicate_rate=0.2, random_state=7)
    second, second_truth = AB.inject_issues(frame, missing_rate=0.2, duplicate_rate=0.2, random_state=7)
    assert frame.equals(original)
    assert first.equals(second)
    assert first_truth == second_truth


def test_compatibility_manifest_is_complete_and_stable():
    result = AB.compatibility_check()
    assert result["ok"] is True
    assert result["missing"] == []
    assert result["version"] == "2.0.0"
    assert result["api_status"] == "stable"
    assert result["v1_api_count"] >= 16
    assert result["v2_api_count"] >= 18


def test_release_documentation_exists():
    required = ["START_HERE_PHASE_7.md", "V2_PHASE_7_SETUP_AND_RELEASE_GUIDE.md", "PHASE_7_VERIFICATION.txt", "docs/VERSION_2_PHASE_7.md", "docs/MIGRATION_1_TO_2.md", "docs/API_STABILITY.md", "docs/RELEASE_NOTES_2_0.md"]
    for relative in required:
        assert (ROOT / relative).exists(), relative


def test_current_release_files_do_not_claim_alpha():
    files = [ROOT / "pyproject.toml", ROOT / "README.md", ROOT / "src/axiombraid/_version.py", ROOT / "src/axiombraid/cli.py", ROOT / "docs/index.md", ROOT / "docs/INSTALLATION.md", ROOT / "docs/PUBLIC_API.md"]
    for path in files:
        text = path.read_text(encoding="utf-8").lower()
        assert "2.0.0a6" not in text
        assert "development status :: 3 - alpha" not in text
